#!/bin/bash

set -x

projects_file=$1

projects=$(cat ${projects_file})
mkdir -p repos

(
    cd repos
    for project in $projects; do
        [ -d $project ] || git clone lp:~ubuntu-openstack-dev/ubuntu/+source/$project
        cd $project
        git pull --all
        for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|master)$'); do
            git branch --track "${branch##remotes/origin/}" "$branch"
        done
    done
)
